### ISSUE TITLE
Make `uid` key case-insensitive

### ISSUE THREAD

**Issue by plin25** [mebird/PLGSPL#1]
My CSVs come out of PL with the header
`UID,UIN,Username,Name,Role,qid,old_score_perc,submission_id,params,true_answer,submitted_answer,partial_scores,score_perc,feedback`
with capital `UID` as opposed to lower case `uid`, so I get `KeyError: 'uid'` unless I manually fix my CSV file.

**Comment by bevansm** [comment]
Resolved by https://github.com/mebird/PLGSPL/commit/30d2c0af641a6048a4f315599c63d2dd9bd26584.
